//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace refactoradiyos_final.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor_Info
    {
        public int ID { get; set; }
        public string DoctorName { get; set; }
        public string DoctorEmail { get; set; }
        public string Doctorpwd { get; set; }
        public string Doctorepwd { get; set; }
        public string Phone { get; set; }
    }
}
