//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace refactoradiyos_final
{
    using System;
    using System.Collections.Generic;
    
    public partial class Biochemistry
    {
        public long ID { get; set; }
        public string IDNo { get; set; }
        public string HbA1c____ { get; set; }
        public string Fruktozamin { get; set; }
        public string AçlıkGlukoz__mg_dl_ { get; set; }
        public string Sedimantasyon__mm_st_ { get; set; }
        public string Ure__mg_dl_ { get; set; }
        public string Kreatinin__mg_dl_ { get; set; }
        public string UrikAsid__mg_dl_ { get; set; }
        public string Sodyum__mmol_L_ { get; set; }
        public string Potasyum__mmol_L_ { get; set; }
        public string Klorür_mmol_L_ { get; set; }
        public string Kalsiyum__mg_dl_ { get; set; }
        public string Fosfor__mg_dl_ { get; set; }
        public string Albumin__mg_dl_ { get; set; }
        public string ALP__U_L_ { get; set; }
        public string AST__U_L_ { get; set; }
        public string ALT__U_L_ { get; set; }
        public string GGT__U_L_ { get; set; }
        public string Trigliserid__mg_dl_ { get; set; }
        public string HDL__mg_dl_ { get; set; }
        public string LDL__mg_dl_ { get; set; }
        public string Demir__mcg_dl_ { get; set; }
        public string TDBK__mcg_dl_ { get; set; }
        public string Ferritin__ng_ml_ { get; set; }
        public string C_peptid__ng_ml_ { get; set; }
        public string hsCRP__mg_L_ { get; set; }
        public string VitB12__pg_ml_ { get; set; }
        public string Other { get; set; }
    }
}
