//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace refactoradiyos_final
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOS
    {
        public long ID { get; set; }
        public string IDNo { get; set; }
        public bool TProtein { get; set; }
        public bool Albümin { get; set; }
        public bool LDH { get; set; }
        public bool Elektrolitler { get; set; }
    }
}
