//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace refactoradiyos_final
{
    using System;
    using System.Collections.Generic;
    
    public partial class C24_Hour_Urine
    {
        public long ID { get; set; }
        public string IDNo { get; set; }
        public bool TProtein { get; set; }
        public bool Mikroalbumin { get; set; }
        public bool BUN { get; set; }
        public bool Kreatinin { get; set; }
        public bool Sodyum { get; set; }
        public bool Potasyum { get; set; }
        public bool Klorür { get; set; }
        public bool Kalsiyum { get; set; }
        public bool Fosfor { get; set; }
        public bool Amilaz { get; set; }
        public bool UrikAsit { get; set; }
        public string TotalHacim { get; set; }
    }
}
