//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace refactoradiyos_final
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cardiovascular_System
    {
        public int IDNo { get; set; }
        public string SistolikRight { get; set; }
        public string SistolikLeft { get; set; }
        public string DiyastolikRight { get; set; }
        public string DiyastolikLeft { get; set; }
        public string Pulse { get; set; }
        public string DorsalisPedisRight { get; set; }
        public string DorsalisPedisLeft { get; set; }
        public string TibialisRight { get; set; }
        public string TibialisLeft { get; set; }
        public string PosteriorRight { get; set; }
        public string PosteriorLeft { get; set; }
    }
}
