//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace refactoradiyos_final
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clinic_Chemistry
    {
        public int IDNo { get; set; }
        public bool Glukoz { get; set; }
        public bool HbA1c { get; set; }
        public bool Fruktozamin { get; set; }
        public bool BUN { get; set; }
        public bool Kreatinin { get; set; }
        public bool Urik_Asit { get; set; }
        public bool Elektrolitler { get; set; }
        public bool Kalsiyum { get; set; }
        public bool Fosfor { get; set; }
        public bool Magnezyum { get; set; }
        public bool ALP { get; set; }
        public bool AST_SGOT_ { get; set; }
        public bool ALT_SGPT_ { get; set; }
        public bool LDH { get; set; }
        public bool GGT { get; set; }
        public bool CK { get; set; }
        public bool CK_MB { get; set; }
        public bool Amilaz { get; set; }
        public bool Lipaz { get; set; }
        public bool Bilirubinler { get; set; }
        public bool Kolestrol { get; set; }
        public bool Trigliserit { get; set; }
        public bool HDL_Kolestrol { get; set; }
        public bool LDL_Kolestrol { get; set; }
        public bool VLDL_Kolestrol { get; set; }
        public bool Lprotein { get; set; }
        public bool Albümin { get; set; }
        public bool Protein { get; set; }
        public bool Elektroforezi { get; set; }
        public bool Demir_TDBK { get; set; }
        public bool Ferrum { get; set; }
        public bool Ferritinin { get; set; }
        public bool VitB12 { get; set; }
        public bool Folat { get; set; }
        public bool TroponinT { get; set; }
        public bool ProBNP { get; set; }
        public bool hs_CRP { get; set; }
        public bool Amonyak { get; set; }
        public bool Immunfiksisyon { get; set; }
    }
}
