//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace refactoradiyos_final
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coagulation
    {
        public int IDNo { get; set; }
        public bool ProtrombinZamanıINR { get; set; }
        public bool AktivitePTT_aPTT_ { get; set; }
        public bool Fibronojen { get; set; }
        public bool ProteinC { get; set; }
        public bool ProteinS { get; set; }
        public bool ATIII { get; set; }
        public bool FaktörVIII { get; set; }
        public bool FaktörIV { get; set; }
        public bool D_Dimer { get; set; }
        public bool İnvitroKanamaZamanı_PFA_100_ { get; set; }
        public bool KollajenEpinefrin { get; set; }
        public bool KollajenADP { get; set; }
    }
}
