//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace refactoradiyos_final
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complications
    {
        public long ID { get; set; }
        public string IDNo { get; set; }
        public bool RetinopatiVar { get; set; }
        public bool RetinopatiYok { get; set; }
        public bool NefropatiVar { get; set; }
        public bool NefropatiYok { get; set; }
        public bool Periferik { get; set; }
        public bool Subjectif { get; set; }
        public bool EMG { get; set; }
        public bool Otonom { get; set; }
        public bool GIS { get; set; }
        public bool KVS { get; set; }
        public bool GUS { get; set; }
        public bool NöropatiYok { get; set; }
        public bool DislipidemiVar { get; set; }
        public bool DislipidemiYok { get; set; }
        public bool KAHVar { get; set; }
        public bool KAHYok { get; set; }
        public bool PAHVar { get; set; }
        public bool PAHYok { get; set; }
        public bool DiabetesFootVar { get; set; }
        public bool DiabetesFootYok { get; set; }
        public bool AmputasyonVar { get; set; }
        public bool AmputasyonYok { get; set; }
        public bool CharcotVar { get; set; }
        public bool CharcotYok { get; set; }
        public bool HypertensionVar { get; set; }
        public bool HypertensionYok { get; set; }
    }
}
