//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace refactoradiyos_final
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consultation
    {
        public long ID { get; set; }
        public string IDNo { get; set; }
        public string Nurse { get; set; }
        public string Nutritionist { get; set; }
        public string Eye { get; set; }
        public string Nefroloji { get; set; }
        public string Nöroloji { get; set; }
        public string Kardiyoloji { get; set; }
        public string Teeth { get; set; }
        public string Other { get; set; }
    }
}
