//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace refactoradiyos_final
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diabetes_Info
    {
        public int IDNo { get; set; }
        public string StartingDate { get; set; }
        public string InitialShape { get; set; }
        public string Gripe { get; set; }
        public string Reason { get; set; }
        public string Story { get; set; }
    }
}
