//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace refactoradiyos_final
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diabetes_Education
    {
        public long ID { get; set; }
        public string IDNo { get; set; }
        public bool DiabetesEduVar { get; set; }
        public bool DiabetesEduYok { get; set; }
        public bool TBTDuzenli { get; set; }
        public bool TBTDuzensiz { get; set; }
        public bool TBTUymuyor { get; set; }
        public bool ExerciseDuzenli { get; set; }
        public bool ExerciseDuzensiz { get; set; }
        public bool ExerciseUymuyor { get; set; }
        public bool SMBGVar { get; set; }
        public bool SMBGYok { get; set; }
    }
}
