//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace refactoradiyos_final
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor_Account
    {
        [Required(ErrorMessage = "Ener DOCTORID")]
        public int DoctorID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public Nullable<int> Phone { get; set; }
        [DataType(DataType.Password)]
        public string Password { get; set; }
        public int AvatarID { get; set; }
    }
}
