//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace refactoradiyos_final
{
    using System;
    using System.Collections.Generic;
    
    public partial class Endocrine_System
    {
        public int IDNo { get; set; }
        public string Thyroid { get; set; }
        public string Obesity { get; set; }
        public string Acanthosis { get; set; }
        public string Other { get; set; }
    }
}
