//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace refactoradiyos_final
{
    using System;
    using System.Collections.Generic;
    
    public partial class Habits
    {
        public long ID { get; set; }
        public string IDNo { get; set; }
        public bool NonCigarette { get; set; }
        public bool BırakmışCigarette { get; set; }
        public string iciyorCigarette { get; set; }
        public bool NonAlcohol { get; set; }
        public bool bırakmısAlcohol { get; set; }
        public string iciyorAlcohol { get; set; }
    }
}
