//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace refactoradiyos_final
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hormone
    {
        public long ID { get; set; }
        public string IDNo { get; set; }
        public bool T3 { get; set; }
        public bool T4 { get; set; }
        public bool FT3 { get; set; }
        public bool FT4 { get; set; }
        public bool LSH { get; set; }
        public bool AntiTPO { get; set; }
        public bool AntiTG { get; set; }
        public bool TG { get; set; }
        public bool PTH { get; set; }
        public bool LH { get; set; }
        public bool FSH { get; set; }
        public bool Östradiol { get; set; }
        public bool Progesteron { get; set; }
        public bool Prolaktin { get; set; }
        public bool Makroprolaktin { get; set; }
        public bool Testosteron { get; set; }
        public bool SHBG { get; set; }
        public bool p_hCG { get; set; }
        public bool DHEA_S { get; set; }
        public bool Kortizol { get; set; }
        public bool İnsülin { get; set; }
        public bool C_Peptid { get; set; }
    }
}
