//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace refactoradiyos_final
{
    using System;
    using System.Collections.Generic;
    
    public partial class IsletAntibodies
    {
        public long ID { get; set; }
        public string IDNo { get; set; }
        public string ICA { get; set; }
        public string Anti_GAD { get; set; }
        public string IA_2 { get; set; }
        public string IAA { get; set; }
    }
}
