//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace refactoradiyos_final
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicine
    {
        public long ID { get; set; }
        public string IDNo { get; set; }
        public string DiabetesDiagnosis { get; set; }
        public string MedicineName { get; set; }
        public string KanSekeri { get; set; }
        public string LdlDuzeyi { get; set; }
        public string TrigliseridDuzeyi { get; set; }
    }
}
