//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace refactoradiyos_final
{
    using System;
    using System.Collections.Generic;
    
    public partial class Neurological_System
    {
        public long ID { get; set; }
        public string IDNo { get; set; }
        public string DiyapozonRight { get; set; }
        public string DiyapozonLeft { get; set; }
        public string MonofilamentRight { get; set; }
        public string MonofilamentLeft { get; set; }
        public string PatellaRight { get; set; }
        public string PatellaLeft { get; set; }
        public string AchillesRight { get; set; }
        public string AchillesLeft { get; set; }
        public string MotorMotionRight { get; set; }
        public string MotorMotionLeft { get; set; }
    }
}
