//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace refactoradiyos_final
{
    using System;
    using System.Collections.Generic;
    
    public partial class Obstetrik_History
    {
        public int IDNo { get; set; }
        public string Period { get; set; }
        public string Unsteady { get; set; }
        public string Pregnant { get; set; }
        public string Menopause { get; set; }
        public bool Nulliparous { get; set; }
        public Nullable<int> NumberofBirths { get; set; }
        public Nullable<int> Miscarry { get; set; }
        public string Makrozomik { get; set; }
        public string Konjenital { get; set; }
    }
}
