//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace refactoradiyos_final
{
    using System;
    using System.Collections.Generic;
    
    public partial class Other_Endocrine_System
    {
        public long ID { get; set; }
        public string IDNo { get; set; }
        public string TSH__IU_ml_ { get; set; }
        public string FT4__pmol_ml_ { get; set; }
        public string AntiTPO__IU_ml_ { get; set; }
        public string AntiTG__IU_ml_ { get; set; }
        public string Kortizol__mg_dl_ { get; set; }
        public string VitD__mg_dl_ { get; set; }
        public string İPTH { get; set; }
        public string Mikroalbuminüri__mg_day_ { get; set; }
        public string Mikroalbumin_kreatininOranı__mg_g_kr_ { get; set; }
        public string eGFR { get; set; }
        public string EKG { get; set; }
        public string EKO { get; set; }
    }
}
