//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace refactoradiyos_final
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient_Info
    {
        public long ID { get; set; }
        public string IDNo { get; set; }
        public string AppDate { get; set; }
        public string FileNo { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Gender { get; set; }
        public string BirthPlace { get; set; }
        public string BirthDate { get; set; }
        public string MaritalStatus { get; set; }
        public string EduStatus { get; set; }
        public string Job { get; set; }
        public string Salary { get; set; }
    }
}
