//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace refactoradiyos_final
{
    using System;
    using System.Collections.Generic;
    
    public partial class Physical_Examination
    {
        public int IDNo { get; set; }
        public string Length { get; set; }
        public string BKI { get; set; }
        public string Weigth { get; set; }
        public string WaistPerimeter { get; set; }
        public string HipPerimeter { get; set; }
        public string GeneralSituation { get; set; }
    }
}
