//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace refactoradiyos_final
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tumor_Markers
    {
        public long ID { get; set; }
        public string IDNo { get; set; }
        public bool AFP { get; set; }
        public bool CEA { get; set; }
        public bool CA125 { get; set; }
        public bool CA19_9 { get; set; }
        public bool CA15_3 { get; set; }
        public bool CA72_4 { get; set; }
        public bool NSE { get; set; }
        public bool PSA { get; set; }
        public bool SerbestPSA { get; set; }
    }
}
